version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      # - 443:443
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ${LOG_DIR}:/var/log
      - ${PROJECT_DIR}:/var/www/${WEB_ROOT}
      # - /etc/letsencrypt:/etc/letsencrypt
    environment:
      NGINX_HOST: ${NGINX_HOST}
      ACCESS_LOG: ${ACCESS_LOG}
      WEB_ROOT: ${WEB_ROOT}
      TZ: ${TZ}

  php:
    build: ./php
    volumes:
      - ${PROJECT_DIR}:/var/www/${WEB_ROOT}
    environment:
      TZ: ${TZ}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint.d
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}

volumes:
  mysql-data: {}
